### ISSUE TITLE
install as global plugin

### ISSUE THREAD

**Issue by kikkauz** [Elendev/nexus-composer-push#11]
Hello

is it possible to install is as global plugin? I tried but when I then try to push a package I have a 
Fatal error: Uncaught Error: Call to undefined function GuzzleHttp\choose_handler()

Best

kikkauz

**Comment by Elendev** [comment]
Hello,

I've already had some issues with Guzzle since the autoload of functions is not well handled by Composer for the plugins.

I'll have a look, thanks!
