### ISSUE TITLE
'Require Guzzle Functions Manually' is broken

### ISSUE THREAD

**Issue by xrobau** [Elendev/nexus-composer-push#15]
The code is (taking just one example):

        $guzzlepromisesfunctions = $composer->getConfig()->get('home') . '/vendor/guzzlehttp/promises/src/functions_include.php';
        if (!file_exists($guzzlepromisesfunctions)) {
            throw new FileNotFoundException("guzzlehttp/promises/src/functions.php not found, is guzzle installed?");
        }

Firstly, it's checking for `functions_include.php` and then saying `functions.php` is missing, and secondly `$composer->getConfig()->get('home')` returns the $HOME directory - eg /home/fred.

**Comment by tm1000** [comment]
@Elendev please publish a new version to packagist with these fixes!

**Comment by Elendev** [comment]
@xrobau and @tm1000 sorry for the delay, the version 0.1.3 is released!
