### ISSUE TITLE
Optional parameters to add the source tag in the composer package json

### ISSUE THREAD

**Issue by fghamsary** [Elendev/nexus-composer-push#19]
In composer package json file you can have a source tag which can contain type, url and reference which is quiet good to have these for the reference of a code source in a version control to the current package in the repository.
Maybe adding a src-url, src-type, src-ref would be a good idea as optional values.
Of course this part needs the composer repository of nexus to be compatible as well.
https://github.com/sonatype-nexus-community/nexus-repository-composer/issues/55
This issue in the repository has been addressed via a Pull Request as well.
For the compatibility with this feature, which will have a Pull Request shortly.
Thanks in advance.

**Comment by Elendev** [comment]
Hello @fghamsary, let me know when sonatype-nexus-community/nexus-repository-composer#55 has been merged!
Cheers

**Comment by Elendev** [comment]
Fixed by #20
