### ISSUE TITLE
Support for Symfony 5

### ISSUE THREAD

**Issue by dkondrat** [Elendev/nexus-composer-push#24]
Would it be possible to enable support for Symfony 5?

**Comment by ym2048** [comment]
the master version now support Symfony 5，when will it be released？This function is urgently needed，thanks very much

**Comment by Elendev** [comment]
Sorry @ym2048 and @dkondrat, I've released it today, version 0.1.4.
Cheers

**Comment by ym2048** [comment]
@Elendev thanks very much, I install the latest version, and it works ok。
