### ISSUE TITLE
Make compatible with composer 2

### ISSUE THREAD

**Issue by BramG** [Elendev/nexus-composer-push#32]
- elendev/nexus-composer-push 0.2.2 requires composer-plugin-api ^1.1 -> found composer-plugin-api[2.0.0] but it does not match the constraint.

What are the plans to make this compatible with composer 2?

**Comment by BramG** [comment]
See: https://github.com/Elendev/nexus-composer-push/pull/33

**Comment by Elendev** [comment]
I close this issue since it has been resolved.
